INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('2','Gokurakugai',NULL,NULL,'0','0','reading','0',NULL,NULL,'https://sushiscan.fr/catalogue/gokurakugai/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('3','Tsui no Taimashi',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'a8c6395b-aa04-426f-aa09-284ae1c3a1e5','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('4','My Dearest Self with Malice Aforethought',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'43078ddf-c2aa-415d-bccb-97e35a3755fa','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('6','Oyasumi Punpun',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/bonne-nuit-punpun-scan-vf/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('7','Manchuria Opium Squad',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'eb9385a1-c240-4770-9ba9-e35a987a3a20','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('8','Unknown',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'88d19cf6-97f3-4c12-9dc4-3724f401f70a','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('9','Gachiakuta',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/gachiakuta-version-officielle/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('10','Gigantis',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/gigantis/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('11','Starving Anonymous',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/starving-revelation/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('12','Bibliomania',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'d22ae7a1-cfae-475a-a8fc-589ef85eece4','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('14','Gyakusatsu Happy End',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'fa4816db-6ea5-4183-81e5-08495557eb91','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('15','Soloist in a Cage',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/soloist-in-a-cage/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('16','Adabana','NON','https://cdn.myanimelist.net/images/manga/2/242436l.jpg','28','0','reading','0','Drama, Mystery','A horrifying double murder and a shocking confession uncovers a dark secret in this suspenseful criminal drama manga.
 
A small town is shocked by the gruesome murder of a student and a ramen shop owner. Mizuki Aikawa, one of the victims'' best friend and classmate, confesses to the brutal crime. However, a local reporter and Mizuki''s public defenders are convinced there''s more to the story. As the truth unravels, a tale of class, exploitation, and the demands of family is revealed.

(Source: Dark Horse)',NULL,'7e0739fe-7544-47f3-9617-90eb7a1c2cc0','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('17','Lili Men',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/lili-men/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('18','Gannibal',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'a636ca5b-018c-42eb-afd3-2e7037afac86','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('19','The Killer Inside',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/the-killer-inside/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('21','Majo to Yaju',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'65c96c31-90d7-4c8d-bd3f-99156dce81dc','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('22','Biorg Trinity',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'c178430f-2f26-4c22-bb02-a6b0196a17c3','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('23','Mahoutsukai to Aka no Pilgrim',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'eefed759-7eb7-4c91-b69a-ba87299a3814','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('24','Under Ninja',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/under-ninja/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('25','Hakaiju',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'9b570ac3-4294-49cb-a863-915b845018f4','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('26','L''Habitant de l''Infini',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/lhabitant-de-linfini/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('27','After God',NULL,NULL,'0','0','reading','0',NULL,NULL,'https://sushiscan.fr/catalogue/after-god/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('28','Wild Strawberry',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/wild-strawberry/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('29','Levius',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'064e82f1-633b-46d0-adcd-90a023052f4e','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('30','Tomahawk Angel',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'249f5de8-38d2-4cbd-b783-ca0589f1e7b4','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('32','Kimi Shi ni Tamō Koto Nakare',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'ab949b43-aa6a-4448-a60f-1fa957f2a1ce','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('33','Magi',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/la-princesse-et-le-magicien/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('34','Ao no Exorcist',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/blue-exorcist/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('35','Rurouni Kenshin',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'ada4b443-7a2a-4974-862e-c66f1127413b','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('36','Samurai 8',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/the-elusive-samurai/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('37','Shiga Hime',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/shiga-hime/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('38','Dorohedoro',NULL,NULL,'0','0','reading','0',NULL,NULL,'https://sushiscan.net/catalogue/dorohedoro/','34f45c13-2b78-4900-8af2-d0bb551101f4','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('40','Jackals',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'2c6c87c3-9bd1-43c3-b352-56a8974983b2','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('41','All You Need Is Kill',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'7dc523b0-8ecd-40b0-b86c-1ea57c07773c','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('42','Feng Shen Ji',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'8efedcc7-dc18-417a-a32d-a37e111ddb6a','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('43','Fire Punch','Fujimoto, Tatsuki','https://cdn.myanimelist.net/images/manga/2/180430l.jpg','83','0','reading','0','Action, Mystery, Supernatural','In a world ravaged by ice and snow, civilization is on the brink of collapse thanks to the elusive Ice Witch. Fighting against the cold has brought out the worst in humanity, leading to cults, violence, and the persecution of the Blessed—those born with supernatural powers.

Agni and Luna—blessed orphans with regenerative powers—are making the best of their situation within a small society of elders; their affection for each other serves as a distraction from the uninhabitable climate. Nevertheless, what little serenity they have is stolen away when army commander Doma passes through and incinerates the village they are seeking refuge in—Agni''s beloved sister included. Doma''s flames do not extinguish until they have reduced their target to ash, and due to Agni''s remarkable regeneration, he remains ablaze and in constant, excruciating pain.

After nearly a decade of enduring the pain, Agni has conditioned himself to tolerate Doma''s flames. However, his burning vengeance is as fierce as it was on the day Luna was taken from him. As Agni traverses a frozen wasteland, he vows to avenge his sister and kill Doma.

[Written by MAL Rewrite]','https://sushiscan.fr/catalogue/fire-punch/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('44','Mieruko-chan',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'6670ee28-f26d-4b61-b49c-d71149cd5a6e','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('45','Hour of the Zombie',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'f0f62b75-5989-4f32-9b59-ab56abe35fc1','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('46','Wallman',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'35d4ce8e-57e5-4e48-a2bb-7b659d03db14','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('50','Tougen Anki',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'85a99758-de39-471e-9f6d-800547f53d0a','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('51','The Devils of Gods',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'b5b21ca1-bba5-4b9a-8cd1-6248f731650b','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('53','Phantom Seer',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'3a3db59a-aafd-452e-8282-8b61ae60b012','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('54','Site',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/parasite/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('55','Dragon Ball Super',NULL,NULL,'0','0','reading','0',NULL,NULL,'https://sushiscan.fr/catalogue/dragon-ball-super/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('56','Nihon Saikyou Bugeisha Ketteisen',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'b76a0506-5168-431b-8acc-fa340a042f93','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('57','Eden: It''s an Endless World!',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'b1670c6b-05cc-4744-87b7-ab5affc3a215','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('58','Link Click',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'72e51451-4d0c-4a3f-97ff-afb3f819fbfa','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('59','Les Fleurs du Mal',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/les-fleurs-du-mal/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('60','Yomotsu Hegui',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'e86f1b1d-c364-4a71-a2b9-06aefcf5bc05','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('61','I Am a Hero',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'ff5ef336-72d7-45a2-bc69-c2ae8fbfeec8','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('62','Solo',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/emperor-of-solo-play/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('63','Inuyashiki',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/inuyashiki/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('65','Grashros',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'62a9a899-eb67-43da-a2f4-7e8c41e4c8ee','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('66','Jujika no Rokunin',NULL,NULL,'0','0','reading','0',NULL,NULL,NULL,'00446151-d199-45d6-8671-821db1151e6c','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('67','Apocalypse no Toride',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/fortress-of-apocalypse/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('68','20th Century Boys','Urasawa, Naoki','https://cdn.myanimelist.net/images/manga/5/260006l.jpg','249','0','reading','0','Award Winning, Drama, Mystery, Sci-Fi','As the 20th century approaches its end, people all over the world are anxious that the world is changing. And probably not for the better.

Kenji Endou is a normal convenience store manager who is just trying to get by. But when he learns that one of his old friends going by the name "Donkey" has suddenly committed suicide and that a new cult led by a figure known as "Friend" is becoming more notorious, Kenji starts to feel that something is not right. With a few key clues left behind by his deceased friend, Kenji realizes that this cult is much more than he ever thought it would be—not only is this mysterious organization directly targeting him and his childhood friends, but the whole world also faces a grave danger that only the friends have the key to stop.

Kenji''s simple life of barely making ends meet is flipped upside down when he reunites with his childhood friends, and together they must figure out the truth of how their past is connected to the cult, as the turn of the century could mean the possible end of the world.

[Written by MAL Rewrite]','https://sushiscan.fr/catalogue/20th-century-boys-perfect-edition/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('69','Dead Dead Demons Dededede Destruction',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'fc7f2c19-0a26-4d89-9505-332fcb7d60c6','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('74','The Bugle Call',NULL,NULL,'0','0','reading','0',NULL,NULL,'https://sushiscan.fr/catalogue/the-bugle-call/',NULL,'1');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('75','Go Go Loser Ranger',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'a958abd8-745d-4f47-9c4d-89abae30f5df','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('76','Heart Gear',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'dcc3f064-9eee-44c1-b409-f6df242a3496','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('77','Dear Anemone',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'fddba606-d598-40b8-9ba5-f69a129305eb','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('78','Homunculus',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'231d5196-1f41-4eba-af8d-841d40bc548d','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('79','Tenkaichi',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'b76a0506-5168-431b-8acc-fa340a042f93','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('80','Mother Parasite',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/mother-parasite/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('81','Shin Zero',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'2121520a-595c-477c-9f26-8e02af741f97','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('82','Fool Night',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/fool-night/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('84','Ubel Blatt',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'8a3e22a6-949a-4540-bfbf-559b8cae30f9','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('85','Nito Exorcist',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'8be11cb2-873b-4fbe-b208-118140698435','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('86','Die Wergelder',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/die-wergelder/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('87','Centuria',NULL,NULL,'0','0','reading','0',NULL,NULL,'https://sushiscan.fr/catalogue/centuria/',NULL,'1');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('88','Mad',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/samadhi/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('89','Tower Dungeon',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/tower-dungeon/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('90','Magus of the Library',NULL,NULL,'0','0','to_read','0',NULL,NULL,'https://sushiscan.fr/catalogue/magus-of-the-library/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('91','Parashoppers',NULL,NULL,'0','0','to_read','0',NULL,NULL,NULL,'eab951af-0bf8-408e-9d03-cd729c78817f','0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('92','One Piece','Eiichiro Oda','https://upload.wikimedia.org/wikipedia/en/9/90/One_Piece%2C_volume_61.jpg','1108','450','reading','5','Shōnen, Aventure','Monkey D. Luffy explore une mer remplie de pirates et de trésors pour devenir le Roi des Pirates.','https://sushiscan.fr/catalogue/one-piece-episode-a/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('93','Demon Slayer','Koyoharu Gotouge','https://upload.wikimedia.org/wikipedia/en/4/44/Kimetsu_no_Yaiba_volume_1.png','205','205','completed','4','Shōnen, Fantaisie','Tanjiro Kamado, un jeune garçon dont la famille a été massacrée par des démons.','https://sushiscan.fr/catalogue/demon-slayer-school-days/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('94','Jujutsu Kaisen','Akutami Gege','https://uploads.mangadex.org/covers/c52b2ce3-7f95-469c-96b0-479524fb7a1a/6d9134b2-21ea-4d02-ac2b-7c0d1c6a2aaa.jpg.512.jpg','271','236','reading','4','Action, Adventure, Horror','Yuuji est un jeune étudiant qui excelle dans le sport, notamment dans l''athlétisme, mais qui a un immense poil dans la main. Du coup, au lieu de parfaire ses capacités physiques qui pourraient lui permettre de devenir le meilleur de l''établissement, il s''est inscrit au club de recherches occultes du lycée. Son petit train-train va changer du tout au tout lorsqu''un véritable esprit malfaiteur vient menacer son école…

---

Maison d''édition FR : **Ki-oon**','https://sushiscan.fr/catalogue/jujutsu-kaisen-modulo/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('95','Vinland Saga','Yukimura, Makoto','https://cdn.myanimelist.net/images/manga/2/188925l.jpg','224','1','reading','5','Action, Adventure, Award Winning, Drama','Thorfinn, son of one of the Vikings'' greatest warriors, is among the finest fighters in the merry band of mercenaries run by the cunning Askeladd, an impressive feat for a person his age. However, Thorfinn is not part of the group for the plunder it entails—instead, for having caused his family great tragedy, the boy has vowed to kill Askeladd in a fair duel. Not yet skilled enough to defeat him, but unable to abandon his vengeance, Thorfinn spends his boyhood with the mercenary crew, honing his skills on the battlefield among the war-loving Danes, where killing is just another pleasure of life.

One day, when Askeladd receives word that Danish prince Canute has been taken hostage, he hatches an ambitious plot—one that will decide the next King of England and drastically alter the lives of Thorfinn, Canute, and himself. Set in 11th-century Europe, Vinland Saga tells a bloody epic in an era where violence, madness, and injustice are inescapable, providing a paradise for the battle-crazed and utter hell for the rest who live in it.

[Written by MAL Rewrite]

Included one-shots:
Volume 23: Sayounara ga Chikai node (For Our Farewell Is Near)
Volume 25: "Assassin''s Creed Valhalla" Collab Bangai-hen (Assassin''s Creed x Vinland Saga)','https://sushiscan.fr/catalogue/saga-vinland/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('96','Chainsaw Man','Tatsuki Fujimoto','https://upload.wikimedia.org/wikipedia/en/f/fc/Chainsawman.jpg','0','0','reading','0','Shōnen, Horreur','Denji, un jeune homme endetté qui fusionne avec son chien-démon Pochita.','https://sushiscan.fr/catalogue/chainsaw-man-version-officielle/',NULL,'0');
INSERT OR IGNORE INTO mangas (id,title,author,cover_url,total_chapters,current_chapter,status,rating,genre,synopsis,reader_url,mangadex_id,favorite) VALUES ('279','Berserk','Kentaro Miura','https://uploads.mangadex.org/covers/801513ba-a712-498c-8f57-cae55b38cc92/81e1c82d-6672-400c-8c58-4ff9bfb89031.jpg.512.jpg','364','0','reading','0',NULL,NULL,'https://sushiscan.fr/catalogue/berserk-le-chevalier-du-dragon-des-flammes/','801513ba-a712-498c-8f57-cae55b38cc92','0');